services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-80}:${CONTAINER_PORT:-80}"
    volumes:
      - /usr/share/nginx/html
    environment:
      - NODE_ENV=production
